### ISSUE TITLE
(RuntimeError) missing prerequisite: 'convert'

### ISSUE THREAD

**Issue by Masynchin** [elixir-mogrify/mogrify#104]
Following code raises this error:
```elixir
defmodule ImageText do
  @moduledoc """
  Documentation for `ImageText`.
  """

  @doc """
  Hello world.

  ## Examples

      iex> ImageText.hello()
      :world

  """
  def hello do
    :world
  end

  def create do
    import Mogrify

    %Mogrify.Image{path: "test.png", ext: "png"}
    |> custom("size", "280x280")
    |> custom("background", "#000000")
    |> create(path: ".")
  end
end
```

Full traceback:
```
C:\expro\image_text>iex -S mix
Interactive Elixir (1.13.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ImageText.hello()
:world
iex(2)> ImageText.create()
** (RuntimeError) missing prerequisite: 'convert'
    (mogrify 0.9.1) lib/mogrify.ex:421: Mogrify.cmd_magick/3
    (mogrify 0.9.1) lib/mogrify.ex:80: Mogrify.create/2
```

**Comment by route** [comment]
Cause you don’t have imagemagick installed?

**Comment by Masynchin** [comment]
> Cause you don’t have imagemagick installed?

I installed it via their launcher. I thinked it will be added to PATH automatically, but it wasn't. Thanks for answering
